!classDefinition: #BaseDeDatosTest category: #'TP CarmenSandiegoCamila'!
TestCase subclass: #BaseDeDatosTest
	instanceVariableNames: 'factory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TP CarmenSandiegoCamila'!

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !

!BaseDeDatosTest methodsFor: 'as yet unclassified'!
! !


!classDefinition: #DetectiveTest category: #'TP CarmenSandiegoCamila'!
TestCase subclass: #DetectiveTest
	instanceVariableNames: 'factory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TP CarmenSandiegoCamila'!

!DetectiveTest methodsFor: 'as yet unclassified'!
! !


!DetectiveTest methodsFor: 'detective tardanzas'!
! !

!DetectiveTest methodsFor: 'detective tardanzas'!
! !

!DetectiveTest methodsFor: 'detective tardanzas'!
! !


!DetectiveTest methodsFor: 'detective toma parametros'!
! !

!DetectiveTest methodsFor: 'detective toma parametros'!
! !

!DetectiveTest methodsFor: 'detective toma parametros'!
! !

!DetectiveTest methodsFor: 'detective toma parametros'!
! !

!DetectiveTest methodsFor: 'detective toma parametros'!
! !


!DetectiveTest methodsFor: 'detective viaja'!
! !

!DetectiveTest methodsFor: 'detective viaja'!
! !

!DetectiveTest methodsFor: 'detective viaja'!
! !

!DetectiveTest methodsFor: 'detective viaja'!
! !

!DetectiveTest methodsFor: 'detective viaja'!
! !

!DetectiveTest methodsFor: 'detective viaja'!
! !


!DetectiveTest methodsFor: 'detective interroga'!
! !

!DetectiveTest methodsFor: 'detective interroga'!
! !

!DetectiveTest methodsFor: 'detective interroga'!
! !

!DetectiveTest methodsFor: 'detective interroga'!
! !

!DetectiveTest methodsFor: 'detective interroga'!
! !

!DetectiveTest methodsFor: 'detective interroga'!
! !


!DetectiveTest methodsFor: 'detective pierde la partida'!
! !


!classDefinition: #OrdenDeArrestoTest category: #'TP CarmenSandiegoCamila'!
TestCase subclass: #OrdenDeArrestoTest
	instanceVariableNames: 'factory'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TP CarmenSandiegoCamila'!

!OrdenDeArrestoTest methodsFor: 'as yet unclassified'!
! !

!OrdenDeArrestoTest methodsFor: 'as yet unclassified'!
! !


!classDefinition: #PaisesTest category: #'TP CarmenSandiegoCamila'!
TestCase subclass: #PaisesTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TP CarmenSandiegoCamila'!
!PaisesTest commentStamp: '<historical>' prior: 0!
nil!